=== gaelrottier/M1/TechnoXML/build/classes/fr/miage/m1/tp1/forrest.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT a (object)>
<!ATTLIST a
    href NMTOKEN #REQUIRED
    xlink:href NMTOKEN #REQUIRED
    xlink:role CDATA #REQUIRED
    xmlns:xlink CDATA #FIXED "http://www.w3.org/1999/xlink"
>
<!ELEMENT auteur (nom,prenom)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT description (a|hr|p|script)*>
<!ATTLIST description
    Style NMTOKEN #REQUIRED
    style NMTOKEN #REQUIRED
    xml:space NMTOKEN #REQUIRED
    xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT document (titre,auteur,description,remarques,xml_parse)>
<!ELEMENT hr EMPTY>
<!ATTLIST hr width NMTOKEN #REQUIRED>
<!ELEMENT i (#PCDATA|b)*>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT object EMPTY>
<!ATTLIST object xlink:href NMTOKEN #REQUIRED>
<!ELEMENT p (#PCDATA|i)*>
<!ATTLIST p
    align NMTOKEN #IMPLIED
    xml:space NMTOKEN #IMPLIED
>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT remarques (#PCDATA)>
<!ELEMENT script (#PCDATA)>
<!ATTLIST script language NMTOKEN #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ATTLIST titre
    Style NMTOKEN #REQUIRED
    style NMTOKEN #REQUIRED
>
<!ELEMENT xml_parse EMPTY>
<!ATTLIST xml_parse processor NMTOKEN #REQUIRED>
<!-- <?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT document (titre, auteur, description, remarques, xml_parse)>
    <!ELEMENT titre (#PCDATA)>
        <!ATTLIST titre style CDATA #REQUIRED>
    <!ELEMENT auteur (nom, prenom)>
        <!ELEMENT nom (#PCDATA)>
        <!ELEMENT prenom (#PCDATA)>
    <!ELEMENT description (p+, hr, a, script)>
        <!ATTLIST description xmlns CDATA #REQUIRED>
        <!ATTLIST description style CDATA #REQUIRED>
        <!ATTLIST description xml:space CDATA #REQUIRED>
        <!ELEMENT p (b|i)>
            <!ATTLIST p xml:space CDATA #IMPLIED>
            <!ATTLIST p align CDATA #IMPLIED>
            <!ELEMENT i (#PCDATA)>
                <!ELEMENT b (#PCDATA)>
        <!ELEMENT hr (ANY)>
        <!ELEMENT a (object)>
        <!ELEMENT script (#PCDATA)>
    <!ELEMENT remarques (#PCDATA)>
    <!ELEMENT xml_parse EMPTY>


-->

=== gaelrottier/M1/TechnoXML/src/fr/miage/m1/tp1/forrest.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<?xml-stylesheet type="text/xsl" href="fg.xsl"?>-->
<!-- &#224; relire -->
<?robots index="yes" follow="no"?>
<!DOCTYPE document SYSTEM "forrest.dtd">
<document>
    <titre style="bold" Style="big">Mes m&#233;moires</titre>
    <auteur>
        <nom>Gump</nom>
        <prenom>Forrest</prenom>
    </auteur>
    <description xmlns="http://www.w3.org/1999/xhtml"
                 style="bold" Style="big" xml:space="preserve">
        <!-- &#224; partir d'ici, on peut utiliser 
        des &#233;l&#233;ments HTML et d'autres aussi
        c'est pratique pour du contenu
        documentaire -->
        <p xml:space="default" align="center">Ma maman disait
        toujours : &#xA; "<i>la vie c'est comme une 
            bo&#238;te de <b>chocolat</b>, on ne sait jamais
            sur quoi on va tomber</i>".</p>
            <hr width="10000em"/>
            <a  xlink:href="bubbagump.avi"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                href="bubbagump.avi"
                xlink:role="mon film">
                <object xlink:href="bubbagump.avi"/>
            </a>
            <script language="JavaScript">
                <![CDATA[
                function check() {
                for (int i=10; i>0; i++) {
                if ( a[b[i]] >5 ) break;
                }
                }
                ]]>
        <!-- v&#233;rifier si la boucle doit s'&#233;crire
        avec i&#45;&#45; et pas i++ -->
            </script>
            <p>La suite, je ne m'en souviens plus...</p>
        </description>
    <remarques>
        Mon document ne parse pas
    </remarques>
    <xml_parse processor="JAXP"/>
</document>
